dataAnalysisTool/urls.py
from django.urls import path, include

from .views import simple,\
                   plot_matlibplot_all,\
                   Plot_chart_js, \
                    show_menu, \
                    HomeView, \
                    ShowChart, \
                    ShowChart_test
                    # demographics,\


app_name = 'dataAnalysisTool'
urlpatterns = [
    # simple set of data plot to matplotlib
    # path('charts/simple/', simple, name='simple'),
    # matplotlib version
    path('charts/plot_matlib/', plot_matlibplot_all, name='plot_matplotlib_all'),
    # similar to the final
    # path('charts/chart_data/', Plot_chart_js.as_view(), name='plot_chart_js'),
    # charts/plot_chart_js/ is waiting to be linear - probably not really needed
    # path('charts/plot_chart_js/', HomeView.as_view(), name='plot_chart_js'),
    path('charts/plot_charts/', ShowChart.as_view(), name='chart_js_allplots'),
    path('charts/test/', ShowChart_test.as_view(), name='test'),

]

#dataAnalysisTool/charts/simple/

hum_temp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('uploader/', include('uploader.urls')),
    path('dataAnalysisTool/', include('dataAnalysisTool.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_program_view
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/home/')),
    path('home/', home_view, name='home'),
    path('about_program/', about_program_view, name='about_program'),

]

uploader/urls.py
from django.conf.urls import url
from django.urls import path, include

from uploader.views import(
    list_view,
    FileFieldFormView,
    directory_load_view,
)


app_name = 'uploader'

urlpatterns = [
    path('load/', list_view, name='list'),
    path('load_multiple/', FileFieldFormView.as_view(), name='multiple_load'),
    path('load_directory/', directory_load_view, name='directory_load')
]

# uploader/load_directory/

pages/templates/about_program.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container bg-light px-5 py-5">

    <div class="m-5">
        <p>
        Humidity Plotter is a program that plots graphs of humidity and temperature at one series and many series
        graphs. The program is designed to present data of different sectors in the factory.
            The data are processed and merged together automatically.
        A web application is only an addition to a  desktop application. The author, Piotr Mieczkowski.
    </p>
    </div>
    <div class="d-flex justify-content-center align-items-center p-3">
        <img src="{% static 'images/graph_sample.jpg' %}" class="img-fluid" alt="sample image">
    </div>
    <div class="d-flex justify-content-center align-items-center p-3">
        <p class="fst-italic">Snapshot of the graph example.</p>
    </div>
</div>

{% endblock %}

pages/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Piotr coding</title>
<!--    <link href="{% static 'products/main.css' %}" rel="stylesheet" type="text/css" />-->

<!--    <link href="{{ STATIC_URL }}main.css" rel="stylesheet" type="text/css" />-->

</head>
<body class="bg-dark.bg-gradient">

{% include "navbar.html" %}

{% comment %}
    {{ STATIC_URL }}main.css
    {% include 'navbar.html' %}
{% endcomment %}

    <div class="box_list">
        {% block content %}
        This text will be replaced
        {% endblock %}
    </div>
    {% block content2 %}
    {% endblock %}

    {% block content3 %}
    {% endblock %}

</body>
</html>

pages/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Home Humidity Plotter</title>
{% endblock title %}

{% block content %}

<div class="container">

    <div class="bg-light p-5 rounded">
        <h1>Program plotting Humidity and Temperature</h1>
        <p class="lead">
            Program plots data in Chart_js. Please, open the whole directory, when the WILPO data are available,
            Program will scan and find all relevant files. Merge them and create one data table.
            If you do not have data, please choose sample data.
        </p>
        <div class="d-grid gap-5 d-flex justify-content-center mt-5">
                <a class="btn btn-lg btn-primary btn-block" href="{% url 'dataAnalysisTool:chart_js_allplots' %}" role="button">Load sample data</a>
                <a class="btn btn-lg btn-primary btn-block" href="{% url 'uploader:directory_load' %}" role="button">Load data</a>
        </div>

        <div class="d-flex justify-content-center align-items-center p-5 m-5">
        <img src="{% static 'images/graph_green.jpg' %}" class="img-fluid" alt="sample image">
    </div>

    </div>
{% endblock %}

{% block content2 %}
{% endblock %}

pages/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
  <div class="container-fluid">

    <span class="navbar-brand">Humidity plotter</span>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" role="navigation" id="navbarCollapse">

      <ul class="navbar-nav mx-auto me-auto mb-2 mb-md-0">
        <li class="nav-item" role="navigation">
          <a class="nav-link" id="home-page" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item" role="navigation">
          <a class="nav-link" id="sample-page" aria-current="page" href="{% url 'dataAnalysisTool:chart_js_allplots' %}">Sample Plot</a>
        </li>
        <li class="nav-item" role="navigation">
          <a class="nav-link" id="about-page" aria-current="page" href="{% url 'about_program' %}">About the page</a>
        </li>

        {% comment %}
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        {% endcomment %}

      </ul>

    </div>
  </div>
</nav>




<script>
  const currentLocation = location.href;
  const menuItem = document.querySelectorAll('a');
  const menuLength = menuItem.length;
  for(let i = 0; i < menuLength; i++){
    if(menuItem[i].href ===  currentLocation){
      menuItem[i].className = "nav-link active"
    }
  }
</script>